
PLANET_IN_HOUSE = {
    # 1st House
    "Sun_1": "Sun in the 1st House: You have a strong sense of self, vitality, and authority. You are a natural leader but may be prone to ego.",
    "Moon_1": "Moon in the 1st House: You are sensitive, emotional, and intuitive. Your appearance and mood may fluctuate.",
    "Mars_1": "Mars in the 1st House: You are energetic, courageous, and ambitious. You may be impulsive or prone to anger.",
    "Mercury_1": "Mercury in the 1st House: You are intelligent, communicative, and curious. You have a youthful appearance.",
    "Jupiter_1": "Jupiter in the 1st House: You are optimistic, wise, and generous. You generally enjoy good health and respect.",
    "Venus_1": "Venus in the 1st House: You are charming, attractive, and peace-loving. You enjoy luxury and relationships.",
    "Saturn_1": "Saturn in the 1st House: You are disciplined, serious, and hardworking. Success comes later in life.",
    "Rahu_1": "Rahu in the 1st House: You are unconventional and ambitious. You may go through identity transformations.",
    "Ketu_1": "Ketu in the 1st House: You are introverted and spiritual. You may feel detached from the world.",

    # 2nd House
    "Sun_2": "Sun in the 2nd House: You are financially independent and authoritative in speech.",
    "Moon_2": "Moon in the 2nd House: Your finances may fluctuate. You are emotionally attached to family.",
    "Mars_2": "Mars in the 2nd House: You speak directly and may have arguments over money.",
    "Mercury_2": "Mercury in the 2nd House: You are clever with numbers and communication.",
    "Jupiter_2": "Jupiter in the 2nd House: You are blessed with wealth and truthful speech.",
    "Venus_2": "Venus in the 2nd House: You have a pleasant voice and enjoy spending on luxury.",
    "Saturn_2": "Saturn in the 2nd House: You are frugal and accumulate wealth slowly.",
    "Rahu_2": "Rahu in the 2nd House: You may have unconventional sources of income or speech.",
    "Ketu_2": "Ketu in the 2nd House: You are detached from material wealth.",

    # 3rd House
    "Sun_3": "Sun in the 3rd House: You are courageous and self-made.",
    "Moon_3": "Moon in the 3rd House: You are imaginative and love travel.",
    "Mars_3": "Mars in the 3rd House: You are a risk-taker and have strong siblings.",
    "Mercury_3": "Mercury in the 3rd House: You are skilled in writing and communication.",
    "Jupiter_3": "Jupiter in the 3rd House: You are philosophical and a good guide.",
    "Venus_3": "Venus in the 3rd House: You are artistic and have good relations with siblings.",
    "Saturn_3": "Saturn in the 3rd House: You are persistent and overcome obstacles.",
    "Rahu_3": "Rahu in the 3rd House: You are brave and unconventional.",
    "Ketu_3": "Ketu in the 3rd House: You may have breaks in communication.",

    # 4th House
    "Sun_4": "Sun in the 4th House: You are proud of your heritage but may have ego clashes at home.",
    "Moon_4": "Moon in the 4th House: You are emotionally attached to your mother and home.",
    "Mars_4": "Mars in the 4th House: You have property potential but domestic life may be turbulent.",
    "Mercury_4": "Mercury in the 4th House: You value education and have a lively home.",
    "Jupiter_4": "Jupiter in the 4th House: You have a large, happy home and good education.",
    "Venus_4": "Venus in the 4th House: You have a beautiful home and vehicles.",
    "Saturn_4": "Saturn in the 4th House: You may have a strict upbringing or old property.",
    "Rahu_4": "Rahu in the 4th House: You may live in foreign lands or have unusual housing.",
    "Ketu_4": "Ketu in the 4th House: You are spiritual but detached from home life.",

    # 5th House
    "Sun_5": "Sun in the 5th House: You are creative and authoritative.",
    "Moon_5": "Moon in the 5th House: You are romantic and emotionally invested in children.",
    "Mars_5": "Mars in the 5th House: You are competitive and passionate.",
    "Mercury_5": "Mercury in the 5th House: You are intelligent and good at speculation.",
    "Jupiter_5": "Jupiter in the 5th House: You are wise and blessed with children.",
    "Venus_5": "Venus in the 5th House: You are artistic and romantic.",
    "Saturn_5": "Saturn in the 5th House: You are disciplined in studies but serious.",
    "Rahu_5": "Rahu in the 5th House: You have obsessive passions or unconventional children.",
    "Ketu_5": "Ketu in the 5th House: You are intuitive but detached from romance.",

    # 6th House
    "Sun_6": "Sun in the 6th House: You overcome enemies and have good vitality.",
    "Moon_6": "Moon in the 6th House: You serve others but may have health issues.",
    "Mars_6": "Mars in the 6th House: You are a fighter and win debates.",
    "Mercury_6": "Mercury in the 6th House: You are analytical but prone to worry.",
    "Jupiter_6": "Jupiter in the 6th House: You are helpful to enemies.",
    "Venus_6": "Venus in the 6th House: You may have issues in relationships.",
    "Saturn_6": "Saturn in the 6th House: You work hard and serve tirelessly.",
    "Rahu_6": "Rahu in the 6th House: You defeat rivals easily.",
    "Ketu_6": "Ketu in the 6th House: You have mysterious ailments.",

    # 7th House
    "Sun_7": "Sun in the 7th House: You seek a partner with status. Ego can be an issue.",
    "Moon_7": "Moon in the 7th House: You seek emotional security in relationships.",
    "Mars_7": "Mars in the 7th House: You are passionate but partnerships can be volatile.",
    "Mercury_7": "Mercury in the 7th House: You want an intelligent and youthful partner.",
    "Jupiter_7": "Jupiter in the 7th House: You have a wise and supportive partner.",
    "Venus_7": "Venus in the 7th House: You have a beautiful and loving marriage.",
    "Saturn_7": "Saturn in the 7th House: You seek a mature and stable partner.",
    "Rahu_7": "Rahu in the 7th House: You are attracted to unconventional partners.",
    "Ketu_7": "Ketu in the 7th House: You are spiritual but detached in relationships.",

    # 8th House
    "Sun_8": "Sun in the 8th House: You are interested in secrets and research.",
    "Moon_8": "Moon in the 8th House: You have strong intuition but emotional fluctuation.",
    "Mars_8": "Mars in the 8th House: You have strong survival instincts.",
    "Mercury_8": "Mercury in the 8th House: You are an investigator.",
    "Jupiter_8": "Jupiter in the 8th House: You have hidden resources and longevity.",
    "Venus_8": "Venus in the 8th House: You benefit from others' wealth.",
    "Saturn_8": "Saturn in the 8th House: You have a long life but face delays.",
    "Rahu_8": "Rahu in the 8th House: You are drawn to the taboo.",
    "Ketu_8": "Ketu in the 8th House: You have spiritual insights.",

    # 9th House
    "Sun_9": "Sun in the 9th House: You respect tradition and father.",
    "Moon_9": "Moon in the 9th House: You love spiritual travel.",
    "Mars_9": "Mars in the 9th House: You fight for your beliefs.",
    "Mercury_9": "Mercury in the 9th House: You love higher learning.",
    "Jupiter_9": "Jupiter in the 9th House: You are a natural teacher and lucky.",
    "Venus_9": "Venus in the 9th House: You appreciate culture and philosophy.",
    "Saturn_9": "Saturn in the 9th House: You value traditional wisdom.",
    "Rahu_9": "Rahu in the 9th House: You challenge orthodox beliefs.",
    "Ketu_9": "Ketu in the 9th House: You are a mystic.",

    # 10th House
    "Sun_10": "Sun in the 10th House: You are ambitious and succeed in career.",
    "Moon_10": "Moon in the 10th House: You are popular in your profession.",
    "Mars_10": "Mars in the 10th House: You are dynamic and executive.",
    "Mercury_10": "Mercury in the 10th House: You work in communication or commerce.",
    "Jupiter_10": "Jupiter in the 10th House: You are respected in your field.",
    "Venus_10": "Venus in the 10th House: You are artistic in your career.",
    "Saturn_10": "Saturn in the 10th House: You work hard for recognition.",
    "Rahu_10": "Rahu in the 10th House: You are fiercely ambitious.",
    "Ketu_10": "Ketu in the 10th House: You may have an unusual career path.",

    # 11th House
    "Sun_11": "Sun in the 11th House: You have powerful friends.",
    "Moon_11": "Moon in the 11th House: You have a wide social circle.",
    "Mars_11": "Mars in the 11th House: You pursue goals aggressively.",
    "Mercury_11": "Mercury in the 11th House: You network effectively.",
    "Jupiter_11": "Jupiter in the 11th House: You have abundant gains.",
    "Venus_11": "Venus in the 11th House: You have wealthy friends.",
    "Saturn_11": "Saturn in the 11th House: You have long-lasting friendships.",
    "Rahu_11": "Rahu in the 11th House: You have material success.",
    "Ketu_11": "Ketu in the 11th House: You are detached from rewards.",

    # 12th House
    "Sun_12": "Sun in the 12th House: You are private and spiritual.",
    "Moon_12": "Moon in the 12th House: You need solitude to recharge.",
    "Mars_12": "Mars in the 12th House: You energy is directed inward.",
    "Mercury_12": "Mercury in the 12th House: You have a vivid imagination.",
    "Jupiter_12": "Jupiter in the 12th House: You are charitable and spiritual.",
    "Venus_12": "Venus in the 12th House: You enjoy private luxuries.",
    "Saturn_12": "Saturn in the 12th House: You are disciplined in isolation.",
    "Rahu_12": "Rahu in the 12th House: You have foreign connections.",
    "Ketu_12": "Ketu in the 12th House: You seek liberation."
}

PLANET_IN_SIGN = {
    # Sun
    "Sun_Aries": "Sun in Aries: Exalted. Leadership, confidence, impulse.",
    "Sun_Taurus": "Sun in Taurus: Stability, persistence, stubborness.",
    "Sun_Gemini": "Sun in Gemini: Communication, versatility, restlessness.",
    "Sun_Cancer": "Sun in Cancer: Emotional, protective, moody.",
    "Sun_Leo": "Sun in Leo: Dignified. Royalty, pride, generosity.",
    "Sun_Virgo": "Sun in Virgo: Analytical, service-oriented, perfectionist.",
    "Sun_Libra": "Sun in Libra: Debilitated. Cooperative but indecisive.",
    "Sun_Scorpio": "Sun in Scorpio: Intense, transformative, secretive.",
    "Sun_Sagittarius": "Sun in Sagittarius: Philosophical, optimistic, honest.",
    "Sun_Capricorn": "Sun in Capricorn: Ambitious, practical, disciplined.",
    "Sun_Aquarius": "Sun in Aquarius: Humanitarian, unconventional, detached.",
    "Sun_Pisces": "Sun in Pisces: Spiritual, compassionate, dreamy.",

    # Moon
    "Moon_Aries": "Moon in Aries: Impulsive, energetic, independent.",
    "Moon_Taurus": "Moon in Taurus: Exalted. Stable emotions, love of comfort.",
    "Moon_Gemini": "Moon in Gemini: Witty, communicative, adaptable.",
    "Moon_Cancer": "Moon in Cancer: Dignified. Intuitive, nurturing, sensitive.",
    "Moon_Leo": "Moon in Leo: Dramatic, warm, seeks attention.",
    "Moon_Virgo": "Moon in Virgo: Detailed, critical, helpful.",
    "Moon_Libra": "Moon in Libra: Diplomatic, social, balanced.",
    "Moon_Scorpio": "Moon in Scorpio: Debilitated. Intense, possessive, deep.",
    "Moon_Sagittarius": "Moon in Sagittarius: Adventurous, straightforward, optimistic.",
    "Moon_Capricorn": "Moon in Capricorn: Reserved, cautious, responsible.",
    "Moon_Aquarius": "Moon in Aquarius: Friendly, humanitarian, unpredictable.",
    "Moon_Pisces": "Moon in Pisces: Psychic, empathetic, artistic.",
    
    # Mars
    "Mars_Aries": "Mars in Aries: Dignified. Pioneer, warrior, aggressive.",
    "Mars_Taurus": "Mars in Taurus: Determined, slow-burning, possessive.",
    "Mars_Gemini": "Mars in Gemini: Argumentative, sharp, scattered.",
    "Mars_Cancer": "Mars in Cancer: Debilitated. Emotional, defensive, protective.",
    "Mars_Leo": "Mars in Leo: Confident, dramatic, born leader.",
    "Mars_Virgo": "Mars in Virgo: Precision, critical, strategic.",
    "Mars_Libra": "Mars in Libra: Diplomatic, aggressive in relationships.",
    "Mars_Scorpio": "Mars in Scorpio: Dignified. Intense, strategic, unyielding.",
    "Mars_Sagittarius": "Mars in Sagittarius: Zealot, adventurous, righteous.",
    "Mars_Capricorn": "Mars in Capricorn: Exalted. Focused, disciplined, successful.",
    "Mars_Aquarius": "Mars in Aquarius: Team-oriented, innovative, rebellious.",
    "Mars_Pisces": "Mars in Pisces: Spiritual warrior, escapist, charitable.",

    # Mercury
    "Mercury_Aries": "Mercury in Aries: Quick-witted, direct, impulsive.",
    "Mercury_Taurus": "Mercury in Taurus: Practical, deliberative, slow-learner.",
    "Mercury_Gemini": "Mercury in Gemini: Dignified. curious, versatile, logical.",
    "Mercury_Cancer": "Mercury in Cancer: Emotional thinker, good memory.",
    "Mercury_Leo": "Mercury in Leo: Expressive, dramatic speech.",
    "Mercury_Virgo": "Mercury in Virgo: Exalted. Analytical, critical, precise.",
    "Mercury_Libra": "Mercury in Libra: Diplomatic, artistic mind.",
    "Mercury_Scorpio": "Mercury in Scorpio: Investigative, sharp tongue.",
    "Mercury_Sagittarius": "Mercury in Sagittarius: Philosophical, blunt.",
    "Mercury_Capricorn": "Mercury in Capricorn: Methodical, serious.",
    "Mercury_Aquarius": "Mercury in Aquarius: Scientific, progressive.",
    "Mercury_Pisces": "Mercury in Pisces: Debilitated. Poetic, confused, imaginative.",

    # Jupiter
    "Jupiter_Aries": "Jupiter in Aries: Pioneer, enthusiastic, confident.",
    "Jupiter_Taurus": "Jupiter in Taurus: Practical wisdom, loves luxury.",
    "Jupiter_Gemini": "Jupiter in Gemini: Teacher, curious, scattered.",
    "Jupiter_Cancer": "Jupiter in Cancer: Exalted. Benevolent, protective.",
    "Jupiter_Leo": "Jupiter in Leo: Generous, grand, dramatic.",
    "Jupiter_Virgo": "Jupiter in Virgo: Detail-oriented, critical wisdom.",
    "Jupiter_Libra": "Jupiter in Libra: Just, balanced, relationship-oriented.",
    "Jupiter_Scorpio": "Jupiter in Scorpio: Occult wisdom, intense.",
    "Jupiter_Sagittarius": "Jupiter in Sagittarius: Dignified. Guru, philosopher.",
    "Jupiter_Capricorn": "Jupiter in Capricorn: Debilitated. Conservative, calculating.",
    "Jupiter_Aquarius": "Jupiter in Aquarius: Humanitarian, scientific.",
    "Jupiter_Pisces": "Jupiter in Pisces: Dignified. Spiritual, compassionate.",

    # Venus
    "Venus_Aries": "Venus in Aries: Passionate, impulsive in love.",
    "Venus_Taurus": "Venus in Taurus: Dignified. Sensual, loyal, artistic.",
    "Venus_Gemini": "Venus in Gemini: Flirtatious, variety-seeking.",
    "Venus_Cancer": "Venus in Cancer: Caring, emotional, attached.",
    "Venus_Leo": "Venus in Leo: Dramatic, loyal, needs attention.",
    "Venus_Virgo": "Venus in Virgo: Debilitated. Critical, practical love.",
    "Venus_Libra": "Venus in Libra: Dignified. Romantic, harmonious.",
    "Venus_Scorpio": "Venus in Scorpio: Intense, possessive, transformative.",
    "Venus_Sagittarius": "Venus in Sagittarius: Adventurous, honest.",
    "Venus_Capricorn": "Venus in Capricorn: Serious, committed, status-oriented.",
    "Venus_Aquarius": "Venus in Aquarius: Unconventional, friendly.",
    "Venus_Pisces": "Venus in Pisces: Exalted. Unconditional love, spiritual.",

    # Saturn
    "Saturn_Aries": "Saturn in Aries: Debilitated. Frustrated, impulsive, hard struggle.",
    "Saturn_Taurus": "Saturn in Taurus: Persistent, works for security.",
    "Saturn_Gemini": "Saturn in Gemini: Logical, disciplined mind.",
    "Saturn_Cancer": "Saturn in Cancer: Insecure, attached to past.",
    "Saturn_Leo": "Saturn in Leo: Ego struggles, seeks authority.",
    "Saturn_Virgo": "Saturn in Virgo: Detail-oriented, perfectionist worker.",
    "Saturn_Libra": "Saturn in Libra: Exalted. Just, balanced, diplomatic.",
    "Saturn_Scorpio": "Saturn in Scorpio: Intense, transformative challenges.",
    "Saturn_Sagittarius": "Saturn in Sagittarius: Philosophical structure.",
    "Saturn_Capricorn": "Saturn in Capricorn: Dignified. Ambitious, organized.",
    "Saturn_Aquarius": "Saturn in Aquarius: Dignified. Scientific, humanitarian.",
    "Saturn_Pisces": "Saturn in Pisces: Spiritual discipline, isolation.",
    
    # Rahu (Nodes take traits of sign lord + sign itself, generic here)
    "Rahu_Aries": "Rahu in Aries: Impulsive ambition.",
    "Rahu_Taurus": "Rahu in Taurus: Materialistic cravings.",
    "Rahu_Gemini": "Rahu in Gemini: Communicative trickery. Exalted?",
    "Rahu_Cancer": "Rahu in Cancer: Emotional turbulence.",
    "Rahu_Leo": "Rahu in Leo: Ambition for power.",
    "Rahu_Virgo": "Rahu in Virgo: Obsessive details.",
    "Rahu_Libra": "Rahu in Libra: Relationship obsession.",
    "Rahu_Scorpio": "Rahu in Scorpio: Occult obsession. Debilitated?",
    "Rahu_Sagittarius": "Rahu in Sagittarius: False guru?",
    "Rahu_Capricorn": "Rahu in Capricorn: Corporate ambition.",
    "Rahu_Aquarius": "Rahu in Aquarius: Scientific innovation.",
    "Rahu_Pisces": "Rahu in Pisces: Spiritual confusion.",
    
    # Ketu
    "Ketu_Aries": "Ketu in Aries: Detached form self.",
    "Ketu_Taurus": "Ketu in Taurus: Detached from comfort.",
    "Ketu_Gemini": "Ketu in Gemini: Confusion.",
    "Ketu_Cancer": "Ketu in Cancer: Emotional detachment.",
    "Ketu_Leo": "Ketu in Leo: Loss of ego.",
    "Ketu_Virgo": "Ketu in Virgo: Mathematical intuition.",
    "Ketu_Libra": "Ketu in Libra: Detached relationships.",
    "Ketu_Scorpio": "Ketu in Scorpio: Deep research. Exalted?",
    "Ketu_Sagittarius": "Ketu in Sagittarius: Moksha karaka.",
    "Ketu_Capricorn": "Ketu in Capricorn: Professional dissatisfaction.",
    "Ketu_Aquarius": "Ketu in Aquarius: Scientific detachment.",
    "Ketu_Pisces": "Ketu in Pisces: Spiritual liberation.",
}
