
RAHU_HOUSE_PURPOSE = {
    1: "Rahu in 1st House: Your purpose is to develop self-identity, independence, and personal confidence. You are here to become a leader and step out of the shadows of others.",
    2: "Rahu in 2nd House: Your purpose is to master financial security, values, and family lineage. You are here to create wealth and define your own self-worth.",
    3: "Rahu in 3rd House: Your purpose is to master communication, courage, and self-effort. You are here to challenge established ideas and use your willpower.",
    4: "Rahu in 4th House: Your purpose is to find emotional stability, domestic happiness, and property. You are here to heal your heart and build a secure home.",
    5: "Rahu in 5th House: Your purpose is to express creativity, romance, and unique intelligence. You are here to leave a legacy through children or creative works.",
    6: "Rahu in 6th House: Your purpose is to serve, heal, and overcome adversity. You are here to master discipline, conquer enemies, and solve complex problems.",
    7: "Rahu in 7th House: Your purpose is to understand relationships and public dealings. You are here to learn how to balance your ego with the needs of partners.",
    8: "Rahu in 8th House: Your purpose is to explore the occult, psychology, and transformation. You are here to uncover secrets and master the cycle of change.",
    9: "Rahu in 9th House: Your purpose is to expand your horizons through foreign travel, higher philosophy, or breaking traditional dogma. You are here to find your own truth.",
    10: "Rahu in 10th House: Your purpose is to achieve high status, career success, and public recognition. You are here to impact the world professionally.",
    11: "Rahu in 11th House: Your purpose is to build large networks, social circles, and achieve major gains. You are here to realize your highest ambitions.",
    12: "Rahu in 12th House: Your purpose is to explore spirituality, foreign lands, and the subconscious. You are here to find liberation and transcend the material world."
}

KETU_HOUSE_KARMA = {
    1: "Ketu in 1st House: You have mastered self-development in the past. Now you must learn to focus on relationships (Rahu in 7th). You may feel detached from your own image.",
    2: "Ketu in 2nd House: You have mastered wealth accumulation in the past. Now you must learn to navigate sudden changes (Rahu in 8th). You may feel indifferent to money.",
    3: "Ketu in 3rd House: You have mastered courage and communication. Now you might seek higher wisdom (Rahu in 9th). You may be quiet and intuitive.",
    4: "Ketu in 4th House: You have mastered domestic life. Now you must focus on career (Rahu in 10th). You may feel detached from your home or mother.",
    5: "Ketu in 5th House: You have mastered creativity and intellect. Now you must focus on social gains (Rahu in 11th). You may face dissatisfaction with children or romance.",
    6: "Ketu in 6th House: You have mastered service and conflict resolution. Now you must seek spiritual liberation (Rahu in 12th). You naturally defeat enemies.",
    7: "Ketu in 7th House: You have mastered relationships. Now you must find yourself (Rahu in 1st). You may feel critical or detached in marriage.",
    8: "Ketu in 8th House: You have mastered the occult and upheavals. Now you must seek stability (Rahu in 2nd). You have deep natural intuition.",
    9: "Ketu in 9th House: You have mastered religion and philosophy. Now you must execute practical courage (Rahu in 3rd). You may question gurus.",
    10: "Ketu in 10th House: You have mastered career and authority. Now you must focus on emotional peace (Rahu in 4th). You may feel unsatisfied with professional success.",
    11: "Ketu in 11th House: You have mastered social networks and gains. Now you must use intelligence (Rahu in 5th). You may have few but deep friends.",
    12: "Ketu in 12th House: You have mastered spirituality and isolation. Now you must work in the world (Rahu in 6th). You are naturally spiritual and nearing liberation."
}

RAHU_NAKSHATRA_PURPOSE = {
    "Ashwini": "Rahu in Ashwini: Desire for speed, healing, and pioneering new beginnings.",
    "Bharani": "Rahu in Bharani: Obsession with creativity, birth/death cycles, and extremes.",
    "Krittika": "Rahu in Krittika: Desire for power, cutting through truth, and digestion of knowledge.",
    "Rohini": "Rahu in Rohini: Obsession with beauty, growth, luxury, and manifestation.",
    "Mrigashira": "Rahu in Mrigashira: The searching soul. Endless desire for new experiences.",
    "Ardra": "Rahu in Ardra: Desire for storm, transformation, and emotional purging.",
    "Punarvasu": "Rahu in Punarvasu: Obsession with renewal, second chances, and returning home.",
    "Pushya": "Rahu in Pushya: Desire for nourishment, spiritual legitimacy, and care.",
    "Ashlesha": "Rahu in Ashlesha: Obsession with psychological depths, kundalini, and binding connection.",
    "Magha": "Rahu in Magha: Desire for lineage, royal status, and connection to ancestors.",
    "Purva Phalguni": "Rahu in Purva Phalguni: Obsession with relaxation, enjoyment, and creative fruits.",
    "Uttara Phalguni": "Rahu in Uttara Phalguni: Desire for relationships, contracts, and social sustenance.",
    "Hasta": "Rahu in Hasta: Obsession with skills, hands, dexterity, and manifesting details.",
    "Chitra": "Rahu in Chitra: Desire for design, structure, and visual perfection.",
    "Swati": "Rahu in Swati: Obsession with independence, movement, and negotiation (Rahu's own star).",
    "Vishakha": "Rahu in Vishakha: Desire for purpose, branched goals, and fixation on achievement.",
    "Anuradha": "Rahu in Anuradha: Obsession with friendship, loyalty, and group devotion.",
    "Jyeshtha": "Rahu in Jyeshtha: Desire for seniority, protection, and overcoming the ego.",
    "Mula": "Rahu in Mula: Obsession with roots, destruction of old, and getting to the core.",
    "Purva Ashadha": "Rahu in Purva Ashadha: Desire for invincibility, water, and emotional purification.",
    "Uttara Ashadha": "Rahu in Uttara Ashadha: Obsession with victory, endurance, and rigid goals.",
    "Shravana": "Rahu in Shravana: Desire for listening, oral tradition, and public reputation.",
    "Dhanishtha": "Rahu in Dhanishtha: Obsession with rhythm, wealth, and musical fame.",
    "Shatabhisha": "Rahu in Shatabhisha: Desire for healing, secrecy, and viewing the infinite (Rahu's own star).",
    "Purva Bhadrapada": "Rahu in Purva Bhadrapada: Obsession with two-faced nature, fire, and penance.",
    "Uttara Bhadrapada": "Rahu in Uttara Bhadrapada: Desire for deep wisdom, water, and control of anger.",
    "Revati": "Rahu in Revati: Obsession with protection, guidance, and the final journey."
}

KETU_NAKSHATRA_KARMA = {
    "Ashwini": "Ketu in Ashwini: You have past mastery of healing and speed. You may feel detached from initiating things.",
    "Bharani": "Ketu in Bharani: You have experienced extremes of life and death. You seek balance now.",
    "Krittika": "Ketu in Krittika: You have wielded power and fire. You may now step back from leadership.",
    "Rohini": "Ketu in Rohini: You have enjoyed great luxury. You are now indifferent to material comfort.",
    "Mrigashira": "Ketu in Mrigashira: You have searched enough. You now seek inner answers.",
    "Ardra": "Ketu in Ardra: You have weathered the storm. You are now calm amidst chaos.",
    "Punarvasu": "Ketu in Punarvasu: You have returned many times. You now seek the final exit.",
    "Pushya": "Ketu in Pushya: You have been the nurturer. You now seek to be nurtured by the divine.",
    "Ashlesha": "Ketu in Ashlesha: You have known deep manipulation. You now seek simple truth.",
    "Magha": "Ketu in Magha (Mula Trikona): You have deep ancestral connection. You are a natural leader but detached from power.",
    "Purva Phalguni": "Ketu in Purva Phalguni: You have had enough rest. You are now action-oriented.",
    "Uttara Phalguni": "Ketu in Uttara Phalguni: You have known marriage. You may feel isolated even in union.",
    "Hasta": "Ketu in Hasta: You have skilled hands. You may now work intuitively without effort.",
    "Chitra": "Ketu in Chitra: You have created structures. You now see the soul within the form.",
    "Swati": "Ketu in Swati: You have wandered freely. You now seek to ground yourself.",
    "Vishakha": "Ketu in Vishakha: You have achieved goals. You realize ambition is endless.",
    "Anuradha": "Ketu in Anuradha: You have been a devoted friend. You may now walk a solitary path.",
    "Jyeshtha": "Ketu in Jyeshtha: You have held seniority. You no longer seek to be the eldest.",
    "Mula": "Ketu in Mula (Own Sign): You are a master of destroying illusions. A strong spiritual placement.",
    "Purva Ashadha": "Ketu in Purva Ashadha: You have felt invincible. You now know true strength is surrender.",
    "Uttara Ashadha": "Ketu in Uttara Ashadha: You have won battles. You now seek peace.",
    "Shravana": "Ketu in Shravana: You have heard it all. You now listen to the silence.",
    "Dhanishtha": "Ketu in Dhanishtha: You have known fame. You prefer anonymity.",
    "Shatabhisha": "Ketu in Shatabhisha: You have healed others. You now heal yourself.",
    "Purva Bhadrapada": "Ketu in Purva Bhadrapada: You have done penance. You are intense but internal.",
    "Uttara Bhadrapada": "Ketu in Uttara Bhadrapada: You have deep wisdom. You are the silent observer.",
    "Revati": "Ketu in Revati: You have guided others. You are ready for the final liberation."
}
